version: 0.0.{build}
init:
- cmd: >-
    SET PATH=%PHPCI_PHP%;%PHPCI_COMPOSER%;%PATH%
    SET COMPOSER_HOME=%PHPCI_COMPOSER%\home
    SET COMPOSER_CACHE_DIR=%PHPCI_COMPOSER%\cache
    SET COMPOSER_NO_INTERACTION=1
    SET PHP=0
    SET ANSICON=121x90 (121x90)
environment:
  PHPCI_CHOCO_VERSION: 7.3.1
  PHPCI_CACHE: C:\tools\phpci
  PHPCI_PHP: C:\tools\phpci\php
  PHPCI_COMPOSER: C:\tools\phpci\composer
install:
- cmd: cinst javaruntime -y
- cmd: set _cd=%cd%
- cmd: cd \tools && mkdir sonar
- cmd: curl -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744.zip
- cmd: 7z x -y sonar-scanner-cli-4.0.0.1744.zip
- cmd: set SONAR_RUNNER_HOME=%cd%\sonar-scanner-4.0.0.1744
- cmd: set path=%path%;%cd%\sonar-scanner-4.0.0.1744\bin
- cmd: sonar-scanner --version
- cmd: cd %_cd%
- cmd: >-
    rem ===

    IF EXIST %PHPCI_CACHE% (SET PHP=1)

    cinst php -i -y --version %PHPCI_CHOCO_VERSION%  --params "/InstallDir:%PHPCI_PHP% /ThreadSafe"

    php -v

    php --ini

    cinst composer -i -y --ia "/DEV=%PHPCI_COMPOSER%"

    composer --version

    pushd %PHPCI_PHP%

    cd

    cd ext

    curl -O https://xdebug.org/files/php_xdebug-2.7.2-7.3-vc15-x86_64.dll

    cd ..

    echo extension=php_curl.dll >> php.ini

    echo zend_extension=php_xdebug-2.7.2-7.3-vc15-x86_64.dll >> php.ini

    powershell cat php.ini -Tail 5

    php -v

    php --ri xdebug


    cd %APPVEYOR_BUILD_FOLDER%

    set path=%path%;%cd%\\vendor\\bin

    curl -O https://github.com/humbug/box/releases/download/3.8.0/box.phar

    composer install --prefer-dist --no-progress --no-interaction
build_script:
- cmd: phing -verbose
- cmd: phing -verbose build-docs
test_script:
- cmd: >-
    phing -verbose tests
artifacts:
- path: .\build
  name: build
- path: .\tests\_output
  name: tests
after_deploy:
on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))